### PR TITLE
Added custom Markdown checkbox design.

### PR DESCRIPTION
**Pull request by kamilatte**

### CODE REVIEW

**Comment by kamilatte** [comment]
*Blows up pankakes with mind*
MA FUCKIN PANCAKES

**Comment by withervt** [comment]
This looks good. However please place the javascript in the folder [`/public/js/@include`](https://github.com/vtuberwiki/wiki/tree/main/public/js/%40include).

It needs to be one file, like so:

CheckBox.js
```javascript
function replaceCheckboxesWithImages() {
        const checkboxes = document.querySelectorAll('input[type="checkbox"]');

        checkboxes.forEach(checkbox => {
            if (checkbox.hasAttribute('checked') && checkbox.hasAttribute('disabled')) {
              checkbox.outerHTML = '<img src="/design/yes.jpg" width="25" height="25">';
            } else if (checkbox.hasAttribute('disabled')) {
                checkbox.outerHTML = '<img src="/design/no.jpg" width="25" height="25">';
            }
        });

        // Remove the script element
        const scriptElement = document.currentScript;
        if (scriptElement) {
            scriptElement.parentElement.removeChild(scriptElement);
        }
    }
    replaceCheckboxesWithImages();
```

**Comment by kamilatte** [comment]
Wtf

**Comment by kamilatte** [comment]
FFS

**Comment by kamilatte** [comment]
WAAA YESSS

**Pull request merged**
